# site config file

# site config
valid_html: Valid HTML
back_to_top: Back to top

# GitHub details
github_username: jbampton
repository: dashboard-2

# site colors
nav_hover_color: red
nav_selected_color: aliceblue

# HTML elements and attributes
# <title>
title: Ruby Google charts text mining dashboard
# meta name="theme-color"
theme_color: '4286f4'

# Text on web pages
# heading at top left of website
nav_heading: Analytics Dashboard